export const assets=[
 {name:'預金',icon:'◉',color:'#688c89',desc:'銀行にあずけるお金。値動きは小さめ。物価が上がると、買える量が減ることも。'},
 {name:'国債',icon:'▥',color:'#6683b3',desc:'国にお金を貸すこと。このゲームは毎年満期になる架空の国債。途中売却は扱いません。'},
 {name:'ものづくり株',icon:'⚙',color:'#e5994b',desc:'海外にも製品を売る架空の会社。円安が追い風になる一方、材料費の上昇は負担に。'},
 {name:'くらし・ケア株',icon:'♡',color:'#c77e88',desc:'医療・介護・地域サービスの架空の会社。需要が増えても、人手不足や費用増の影響を受けます。'},
 {name:'未来エネルギー株',icon:'☀',color:'#74a36a',desc:'省エネや発電に取り組む架空の会社。新技術への期待も、開発がうまくいかないリスクも。'}
];
export const lessons=[
 {tag:'円安と貿易',title:'円安で、まちのパンが値上がり？',news:'海外から買う小麦やエネルギーが高くなりました。一方、海外に製品を売る会社には追い風も。',chain:['円の価値が下がる','輸入する材料が高くなる','お店の費用・家計の負担が増える'],question:'円安が進むと、どんなことが起こりやすい？',options:['輸入品が必ず安くなる','輸入の費用が増え、輸出企業には追い風もある','すべての会社の利益が増える'],answer:1,explain:'同じ1ドルの商品でも、100円から120円になれば必要な円は増えます。輸出で得たドルを円に替える会社には有利な面も。ただし原材料や海外生産の割合によって影響は違います。',deep:'為替は企業に一様には作用しません。輸出企業でも輸入原材料が多いと利益が圧迫されます。ニュースだけで株価は決まりません。',rates:[.005,.012,.09,-.02,.01],inflation:.035,policy:['給食の材料費を支える','省エネ設備を増やす'],effects:[[8,1],[2,8]],tradeoffs:['今の家計を助ける一方、将来の設備に使える予算は減ります。','将来の光熱費を減らす準備。今すぐ困っている家計への支援は小さめです。']},
 {tag:'少子高齢化と働き手',title:'働く人が足りない。どう支える？',news:'地域では介護の利用が増える一方、働き手が不足。会社は賃上げや仕事の自動化を考えています。',chain:['人口の年齢構成が変わる','介護の需要・人手不足が増える','賃金やサービスの費用が変わる'],question:'高齢化で介護の需要が増えたら、会社の利益は？',options:['必ず増える','需要と費用の両方によって変わる','必ずゼロになる'],answer:1,explain:'サービスを使う人が増えても、人件費や設備の費用も増えます。売上が増えることと、利益が増えることは同じではありません。',deep:'社会保障は税金や保険料などで支えられます。負担と給付、今の支援と将来の人材育成のバランスが課題です。',rates:[.006,.014,.02,.08,.025],inflation:.025,policy:['介護サービスを支える','学び直し・人材育成を支える'],effects:[[9,1],[3,7]],tradeoffs:['いま必要なケアが届きやすくなります。人材育成への予算は小さめに。','将来の働き手を育てます。効果が出るには時間がかかります。']},
 {tag:'税金と公共サービス',title:'古くなった橋と、学校の予算。',news:'道路や橋の修理、学校の設備にもお金が必要です。自治体は限られた税収をどう使うか話し合っています。',chain:['家計や会社が税を納める','国・自治体が予算を決める','学校・道路などを支える'],question:'税金の役割として近いものは？',options:['必ず自分が納めた分だけ戻ってくる','公共サービスを社会全体で支える','すべて銀行に預けたままにする'],answer:1,explain:'税金は学校、道路、医療などを支える財源です。必要な人や地域に使われ、自分が納めた額と受けるサービスが一致するとは限りません。',deep:'国債は国の資金調達手段ですが、利払いと返済を考える必要があります。予算には税収以外もあり、このゲームでは簡略化しています。',rates:[.006,.014,.04,.025,.035],inflation:.02,policy:['橋・道路の修理を進める','学校の学習環境を整える'],effects:[[8,2],[3,8]],tradeoffs:['移動や物流の安全を支えます。今年の学校設備への配分は小さめです。','将来の学びを支えます。すべての道路修理を同時には進められません。']},
 {tag:'金利と銀行',title:'金利が上がると、誰がうれしい？',news:'金利が上がりました。預金の利息にはプラスですが、お金を借りて設備を買う会社には負担もあります。',chain:['金利が上がる','預金の利息・借入の費用が増える','家計や会社のお金の使い方が変わる'],question:'金利の上昇で起こりやすいことは？',options:['預金の利息も借入の負担も増える','借りたお金を返さなくてよくなる','すべての株価が上がる'],answer:0,explain:'金利はお金を貸し借りするときの利子の割合。借入の負担が増えると、企業が新しい工場などへの投資を控えることもあります。',deep:'市場金利が上がると、既に発行された固定金利の債券の市場価格は一般に下がります。ゲームの国債は毎年満期の設定なので途中価格は扱いません。',rates:[.018,.025,-.06,-.025,-.09],inflation:.015,policy:['地域の相談・生活支援','企業の省力化を支援'],effects:[[8,1],[2,8]],tradeoffs:['生活の負担を和らげます。設備への支援は小さめに。','将来の生産性を育てますが、効果には時間がかかります。']},
 {tag:'エネルギーと海外',title:'海外の燃料価格が急上昇。',news:'輸入する燃料が高くなり、電気代や輸送費に影響が。省エネへの関心も高まっています。',chain:['海外の燃料価格が上がる','電気代・輸送費が増える','家計と企業が省エネを考える'],question:'投資先を分ければ、損はなくなる？',options:['たくさん分ければ絶対に損しない','一つに集中するほど安全','値動きを抑える効果はあるが、損はありうる'],answer:2,explain:'分散は一つの会社への集中を避ける方法です。ただしエネルギー価格など共通の原因で、複数の会社が同時に影響を受けることもあります。',deep:'異なる値動きの資産を組み合わせるほど分散の効果が期待できます。国内の数社だけでは、地域や業種に偏りが残ります。',rates:[.018,.026,-.07,-.045,.10],inflation:.05,policy:['光熱費の支援をする','断熱・再エネ設備を育てる'],effects:[[9,0],[2,9]],tradeoffs:['今の負担を減らせますが、燃料への依存は残ります。','将来の使用量を減らす備え。すぐにすべての費用が下がるわけではありません。']},
 {tag:'技術と未来の社会',title:'新技術が、まちの仕事を変える。',news:'工場や介護の現場で新しい技術が使われ始めました。便利になる一方、新しいスキルを学ぶ機会も必要です。',chain:['新しい技術に投資する','仕事のやり方が変わる','生産性・雇用・学びに影響する'],question:'投資を考えるとき、大切なのは？',options:['話題の会社なら必ずもうかると考える','社会の変化とリスクを調べ、資金の使い道を考える','昨日上がったものだけ買う'],answer:1,explain:'将来はだれにも確実には分かりません。目的、使う時期、損失に耐えられる範囲を考え、社会の変化と企業の費用・利益の両面を見ることが大切です。',deep:'生産性が高まっても、恩恵が社会全体に自動で均等に広がるとは限りません。再教育や制度の設計も重要です。',rates:[.015,.022,.085,.045,.075],inflation:.02,policy:['仕事の学び直しを支える','新技術の研究を支える'],effects:[[7,4],[2,9]],tradeoffs:['仕事の変化についていく人を支えます。研究予算は小さめです。','将来の可能性を育てますが、研究は成功するとは限りません。']}
];
export function initialState(mode='easy',seed=Math.floor(Math.random()*4294967295)){return {version:1,mode,seed,year:0,phase:'plan',money:100000,priceIndex:1,wellbeing:50,future:50,knowledge:0,allocation:[40,30,10,10,10],policy:null,answer:null,history:[],started:false};}
export function returnsFor(year,seed){const event=lessons[year];return event.rates.map((base,i)=>{if(i<2)return base;let x=(seed^(year*374761393)^(i*668265263))>>>0;x=Math.imul(x^(x>>>13),1274126177);const jitter=((x>>>0)%10001)/10000*.18-.09;return Math.round((base+jitter)*10000)/10000;});}
export function validAllocation(a){return Array.isArray(a)&&a.length===5&&a.every(n=>Number.isFinite(n)&&n>=0&&n<=100&&n%10===0)&&a.reduce((x,y)=>x+y,0)===100;}
export function settle(s){if(s.phase!=='plan'||s.year>=6||!validAllocation(s.allocation)||![0,1].includes(s.policy))throw Error('配分の合計を100%にし、まちの予算を選んでください。');const e=lessons[s.year],rates=returnsFor(s.year,s.seed);const gain=Math.round(s.money*s.allocation.reduce((v,a,i)=>v+a/100*rates[i],0));const money=s.money+gain;const priceIndex=s.priceIndex*(1+e.inflation);const row={year:s.year,money,before:s.money,gain,rates,allocation:[...s.allocation],policy:s.policy,priceIndex,answer:null};return {...s,money,priceIndex,phase:'result',answer:null,wellbeing:Math.min(100,s.wellbeing+e.effects[s.policy][0]),future:Math.min(100,s.future+e.effects[s.policy][1]),history:[...s.history,row]};}
export function answerQuiz(s,index){if(s.phase!=='result'||s.answer!==null||!Number.isInteger(index)||index<0||index>2)throw Error('回答できません');const correct=index===lessons[s.year].answer;return {...s,answer:index,knowledge:s.knowledge+(correct?1:0),history:s.history.map((h,i)=>i===s.year?{...h,answer:index}:h)};}
export function nextYear(s){if(s.phase!=='result'||s.answer===null)throw Error('クイズに回答してください');return {...s,year:s.year+1,phase:s.year===5?'complete':'plan',policy:null,answer:null};}
export function restore(raw){try{const s=JSON.parse(raw);if(s?.version!==1||!['easy','deep'].includes(s.mode)||!Number.isInteger(s.seed)||s.seed<0||s.seed>4294967295||!Number.isInteger(s.year)||s.year<0||s.year>6||!['plan','result','complete'].includes(s.phase)||!Array.isArray(s.history)||typeof s.started!=='boolean')return null;let r=initialState(s.mode,s.seed);r.started=s.started;for(const h of s.history){r.allocation=h.allocation;r.policy=h.policy;r=settle(r);if(h.answer!==null)r=answerQuiz(r,h.answer);if(r.year<s.year)r=nextYear(r);}if(r.year!==s.year||r.phase!==s.phase)return null;if(!Array.isArray(s.allocation)||s.allocation.length!==5||!s.allocation.every(n=>Number.isInteger(n)&&n>=0&&n<=100&&n%10===0)||![null,0,1].includes(s.policy))return null;return {...r,allocation:s.allocation,policy:s.policy};}catch{return null;}}
